image: hseeberger/scala-sbt
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbt-version

cache:
  paths:
    - .

build:
  tags:
    - docker
  script:
    - sbt clean compile

test:
  tags:
    - docker
  script:
    # Execute your project's tests
    - sbt test
