image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
       
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbtVersion

stages:
 - check
 - test
 - deploy

check:
  stage: check
  tags:
    - docker
  script:
    - sbt scalafmtCheckAll scalafmtSbtCheck headerCheck

test:
  stage: test
  only:
    - master
    - development
    - /^mr-.*$/
    - /^issue-.*$/
  tags:
    - docker
  script:
    - sbt clean coverage test coverageReport coverageAggregate
  artifacts:
    paths:
      - target/scala-2.13/scoverage-report
    reports:
      cobertura: target/scala-2.13/coverage-report/cobertura.xml

deploy:
  stage: deploy
  only:
    - master
    - development
    - /^mr-.*$/
    - /^issue-.*$/
  tags:
    - docker
  script:
    - sbt clean doc "set test in assembly := {}" assembly
  artifacts:
    paths:
    - target/scala-2.13/*.jar
    - target/scala-2.13/api
    - core/target/scala-2.13/api
    - docs/target/scala-2.13/api
    - interpreter/target/scala-2.13/api
    - instrumenter/target/scala-2.13/api
    - tessla-compiler/target/scala-2.13/api