image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
       
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbtVersion

test:
  only:
    - master
    - development
    - TesslaCoreProposal
  tags:
    - docker
  script:
    - sbt clean test

deploy:
  only:
    - master
    - development
    - TesslaCoreProposal
  tags:
    - docker
  script:
    - sbt clean assembly
  artifacts:
    paths:
    - target/scala-2.12/*.jar
