image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
       
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbtVersion

check:
  tags:
    - docker
  script:
    - sbt scalafmtCheckAll scalafmtSbtCheck

test:
  only:
    - master
    - development
  tags:
    - docker
  script:
    - sbt clean test

deploy:
  only:
    - master
    - development
  tags:
    - docker
  script:
    - sbt clean doc assembly
  artifacts:
    paths:
    - target/scala-2.13/*.jar
    - target/scala-2.13/api
    - core/target/scala-2.13/api
    - docs/target/scala-2.13/api
    - interpreter/target/scala-2.13/api
    - instrumenter/target/scala-2.13/api
    - tessla-compiler/target/scala-2.13/api