image: hseeberger/scala-sbt
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbt-version

test:
  tags:
    - docker
  script:
    - sbt clean test

deploy:
  tags:
    - docker
  script:
    - sbt clean assembly
  artifacts:
    paths:
    - target/scala-2.12/*.jar
