image: hseeberger/scala-sbt:11.0.3_1.2.8_2.13.0
before_script:
  # Log the Java version
  - java -version
  # Log the sbt version
  - sbt sbtVersion

test:
  only:
    - master
    - development
  tags:
    - docker
  script:
    - sbt clean test

deploy:
  only:
    - master
  tags:
    - docker
  script:
    - sbt clean assembly
  artifacts:
    paths:
    - target/scala-2.12/*.jar
