/*
 * Copyright (c) 2020 Institute of Software Engineering and Programming Languages,
 * University of Lübeck, Germany
 *
 * Modified MIT license:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this binary (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software and the code which is
 * generated by the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package de.uni_luebeck.isp.tessla.core.analyses

import de.uni_luebeck.isp.tessla.core.TesslaAST.Core._
import de.uni_luebeck.isp.tessla.core.TesslaAST.Core

import scala.collection.mutable

object DepthChecker {

  def nestingDepth(spec: Core.Specification): Int = {
    val memTable: mutable.Map[Core.Identifier, Int] = mutable.Map()
    val ins = spec.in.keySet
    val defDepths = spec.definitions.values
      .map(extract)
      .collect {
        case (e: ExternExpression, args) if e.name == "last" || e.name == "delay" => args.head
      }
      .map(nestingDepth(spec.definitions, ins, _, None, memTable))

    val outDepths = spec.out.map(_._1).map(nestingDepth(spec.definitions, ins, _, None, memTable))

    (outDepths ++ defDepths).fold(0)(math.max)
  }

  def nestingDepth(
    streams: Map[Core.Identifier, Core.Expression],
    ins: Set[Core.Identifier],
    stream: Core.ExpressionArg,
    id: Option[Core.Identifier],
    memoized: mutable.Map[Core.Identifier, Int]
  ): Int = {
    def visitChild(child: Core.ExpressionArg): Int = {
      nestingDepth(streams, ins, child, None, memoized)
    }

    stream match {
      case ref: Core.ExpressionRef if ins.contains(ref.id)      => 0
      case ref: Core.ExpressionRef if memoized.contains(ref.id) => memoized(ref.id)
      case ref: Core.ExpressionRef                              => nestingDepth(streams, ins, streams(ref.id), Some(ref.id), memoized)
      case exp: Core.Expression =>
        val childDepth = extract(exp) match {
          case (e: ExternExpression, args) if e.name == "last" || e.name == "delay" =>
            visitChild(args(1))
          case (e, args) =>
            args.map(visitChild).maxOption.getOrElse(0)
        }
        id.foreach(memoized(_) = 1 + childDepth)
        1 + childDepth
    }
  }

  private def extract(e: Core.Expression) = e match {
    case ApplicationExpression(TypeApplicationExpression(e: ExternExpression, _, _), args, _) => (e, args)
    case ApplicationExpression(e: ExternExpression, args, _)                                  => (e, args)
    case _                                                                                    => (e, Seq())
  }
}
