/*
 * Copyright (c) 2020 Institute of Software Engineering and Programming Languages,
 * University of Lübeck, Germany
 *
 * Modified MIT license:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this binary (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software and the code which is
 * generated by the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package de.uni_luebeck.isp.tessla.core.analyses

import de.uni_luebeck.isp.tessla.core.TesslaAST.Core
import de.uni_luebeck.isp.tessla.core.TesslaAST.Core._

import scala.collection.mutable
import de.uni_luebeck.isp.tessla.core.util._

object RecursiveDepthChecker {

  def nestingDepth(spec: Core.Specification): Int = {
    val ins = spec.in.keySet
    val defDepths = spec.definitions.mapVals(extract).collect {
      case (id, (e: ExternExpression, args)) if e.name == "last" || e.name == "delay" =>
        nestingDepth(spec.definitions, ins, args.head, None, id, mutable.Map()).getOrElse(0)
    }

    defDepths.fold(0)(math.max)
  }

  def nestingDepth(
    streams: Map[Core.Identifier, Core.Expression],
    ins: Set[Core.Identifier],
    stream: Core.ExpressionArg,
    id: Option[Core.Identifier],
    origin: Core.Identifier,
    memoized: mutable.Map[Core.Identifier, Option[Int]]
  ): Option[Int] = {
    def visitChild(child: Core.ExpressionArg): Option[Int] = {
      nestingDepth(streams, ins, child, None, origin, memoized)
    }

    stream match {
      case ref: Core.ExpressionRef if ins.contains(ref.id)      => None
      case ref: Core.ExpressionRef if memoized.contains(ref.id) => memoized(ref.id)
      case ref: Core.ExpressionRef                              => nestingDepth(streams, ins, streams(ref.id), Some(ref.id), origin, memoized)
      case exp: Core.Expression =>
        val depth: Option[Int] =
          if (id.contains(origin)) Some(0)
          else {
            extract(exp) match {
              case (e: ExternExpression, args) if e.name == "last" || e.name == "delay" =>
                visitChild(args(1))
              case (e, args) =>
                args.map(visitChild).maxOption.flatten
            }
          }
        val next = depth.map(_ + 1)
        id.foreach(memoized(_) = next)
        next
    }
  }

  private def extract(e: Core.Expression) = e match {
    case ApplicationExpression(TypeApplicationExpression(e: ExternExpression, _, _), args, _) => (e, args)
    case ApplicationExpression(e: ExternExpression, args, _)                                  => (e, args)
    case _                                                                                    => (e, Seq())
  }
}
