/*
 * Copyright (c) 2020 Institute of Software Engineering and Programming Languages,
 * University of Lübeck, Germany
 *
 * Modified MIT license:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this binary (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software and the code which is
 * generated by the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package de.uni_luebeck.isp.tessla.core

import de.uni_luebeck.isp.tessla.core.TesslaAST.Core
import spray.json._

/**
 * Contains functionality to transform annotations of a specification into a Json format.
 * */
object AnnotationsToJson {

  case class Annotation(name: String, args: Map[String, AnnotationValue])
  case class AnnotationValue(value: String, `type`: String)
  case class Stream(name: String, `type`: String, annotations: Seq[Annotation])

  case class Specification(
    global: Seq[Annotation],
    inputs: Seq[Stream],
    outputs: Seq[Stream]
  )

  object JsonProtocol extends DefaultJsonProtocol {
    implicit val annotationFormat: JsonFormat[Annotation] = lazyFormat(jsonFormat2(Annotation))
    implicit val annotationValueFormat: JsonFormat[AnnotationValue] = jsonFormat2(AnnotationValue)
    implicit val streamFormat: JsonFormat[Stream] = jsonFormat3(Stream)
    implicit val specificationFormat: JsonFormat[Specification] = jsonFormat3(Specification)
  }

  import JsonProtocol._

  /**
   * Extract the annotations (including argument names and types) from the specification and return
   * a prettified Json String.
   * */
  def apply(spec: Core.Specification): String = {
    val globals = translateAnnotations(spec.annotations)
    val inputs = spec.in.map {
      case (name, (typ, annotations)) =>
        Stream(name.toString, typ.toString, translateAnnotations(annotations))
    }.toSeq
    val outputs = spec.out.map {
      case (ref, annotations) =>
        Stream(ref.id.toString, ref.tpe.toString, translateAnnotations(annotations))
    }
    val annotationInfo = Specification(globals, inputs, outputs)
    annotationInfo.toJson.prettyPrint
  }

  private def translateAnnotations(annotations: Core.Annotations) =
    annotations.toSeq
      .flatMap {
        case (name, entries) => entries.map((name, _))
      }
      .map {
        case (name, args: Core.RecordConstructorExpression) =>
          val stringified = args.entries.view.mapValues(_._1).mapValues(translateAnnotationValue).toMap
          Annotation(name, stringified)
        case (name, value) =>
          Annotation(name, Map("value" -> translateAnnotationValue(value)))
      }

  // In case of a string literal, take the String value directly instead of printing the literal
  // since that would result in the value being wrapped in quotation marks, which will then be
  // escaped during Json generation, like "\"foo\""
  private def translateAnnotationValue(arg: Core.ExpressionArg): AnnotationValue = arg match {
    case s: Core.StringLiteralExpression => AnnotationValue(s.value, arg.tpe.toString)
    case _                               => AnnotationValue(arg.toString, arg.tpe.toString)
  }
}
