/*
 * Copyright (c) 2020 Institute of Software Engineering and Programming Languages,
 * University of Lübeck, Germany
 *
 * Modified MIT license:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this binary (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software and the code which is
 * generated by the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package de.uni_luebeck.isp.tessla.core

import scala.collection.mutable

/**
 * Applies a reverse topological sort on an arbitrary graph data structure.
 *
  * This is used in the [[TypeChecker]] to check for recursive definitions.
 */
object ReverseTopologicalSort {

  sealed abstract class Result[Node]

  final case class Sorted[Node](nodes: Seq[Node]) extends Result[Node]

  final case class Cycles[Node](nodesInCycles: Seq[Node]) extends Result[Node]

  def sort[Node](startNodes: Iterable[Node])(getChildren: Node => Seq[Node]): Result[Node] = {
    val visited = mutable.Set[Node]()
    val nodesInCycles = mutable.ArrayBuffer[Node]()

    var nodes = List[Node]()

    def go(current: Node, stack: List[Node]): Unit = {
      if (stack.contains(current)) {
        nodesInCycles ++= stack.slice(0, stack.indexOf(current) + 1)
      } else if (!visited.contains(current)) {
        getChildren(current).foreach(go(_, current :: stack))
        visited += current
        nodes = current :: nodes
      }
    }

    startNodes.foreach { startNode =>
      go(startNode, List())
    }
    if (nodesInCycles.isEmpty) {
      Sorted(nodes.reverse)
    } else {
      Cycles(nodesInCycles.toSeq)
    }
  }
}
